version: '3.9'

services:
  bot:
    build: .
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:8
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: